name: manage
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^7.2.0
  freezed_annotation: ^0.14.3
  json_annotation: ^4.1.0
  cupertino_icons: ^1.0.2
  socket_io_client: ^2.0.0
  http: ^0.13.4
  dio: ^4.0.6
  retrofit: any
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.0.0
  video_player: ^2.4.5
  chewie: ^1.3.4
  just_audio: ^0.9.28
  audioplayers: ^1.0.1
  image_picker: ^0.8.5+3
  assets_audio_player: ^3.0.5
  file_picker: ^4.0.0






dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^0.14.5
  json_serializable: ^6.1.1
  build_runner: ^2.1.11
  retrofit_generator: any





  flutter_lints: ^1.0.0


flutter:


  uses-material-design: true

